package EchoApp;


/**
* EchoApp/EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorld.idl
* Domingo, 3 de Maio de 2020 22h50min13s BRT
*/

public interface EchoOperations 
{
  String helloWorldString ();
} // interface EchoOperations
