package EchoApp;


/**
* EchoApp/EchoOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from HelloWorld.idl
* Terça-feira, 5 de Maio de 2020 19h51min31s BRT
*/

public interface EchoOperations 
{
  String helloWorldString ();
  int Fibonacci (int arg);
} // interface EchoOperations
